name: neumedira_farhan_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  build_runner: 2.4.6
  json_serializable: 6.7.1
  json_annotation: 4.8.1
  intl: 0.18.1
  socket_io_client: 2.0.3+1
  lottie: 2.6.0
  flutter_chat_bubble: 2.0.2
  get_storage: 2.1.1
  dio: 5.3.3
  pretty_dio_logger: 1.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
  uses-material-design: true

